### ISSUE TITLE
"Service lifecycle management" to "Specific manager registry" interface

### ISSUE THREAD

**Issue by elekjani** [sonata-nfv/son-mano-framework#193]
Hi,

The service lifecycle management (SLM) service send a YAML descriptor to the specific manager registry (SMR) about the deployed service and the needed SSMs. The YAML is created at son-mano-framework/plugins/son-mano-service-lifecycle-management/son_mano_slm/slm.py:589 and  processed from the son-mano-framework/son-mano-specificmanager/son-mano-specific-manager-registry/son_mano_specific_manager_registry/specificmanagerregistry.py:106 position. It's easy to see that the expected format is not the same as the one that is provided. Which service has an incorrect interface implementation? What is the intended interface (YAML schema?)

Regards,
Janos

**Comment by tsoenen** [comment]
Hi Janos,

We are aware that the current version of the MANO framework contains some API issues between the SLM and the SMR. We are currently working on this, and will provide a fix shortly!

Best,
Thomas

**Comment by tsoenen** [comment]
Fixed with latest updates of SLM and SMR.
