### ISSUE TITLE
IA_termination_response called after vnf_unchain

### ISSUE THREAD

**Issue by tobiasdierich** [sonata-nfv/son-mano-framework#247]
Hi,

I've just noticed that the response callback of the `vnf_unchain` method in the slm is `IA_termination_response` (see [here](https://github.com/sonata-nfv/son-mano-framework/blob/master/plugins/son-mano-service-lifecycle-management/son_mano_slm/slm.py#L1574)). Shouldn't this be `IA_unchain_response` ? I believe, in the current implementation `IA_unchain_response` is never called.

Best regards,
Tobias

**Comment by tsoenen** [comment]
Fixed in branch 3.1. Will be merged in the master in the near future.
