### ISSUE TITLE
Notification of the Mon. Framework

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-mano-framework#282]
Hi, @tsoenen and @pkarkazis 

I'm not sure how the MANO notifies Monitoring when there's a new service instance available... is it a message published on an internal MQ topic? If so, which is the message? 

Now that we have the SLA and the Policy Managers, we might reuse the same topic for their further actions...

**Comment by efotopoulou** [comment]
@jbonnet thanks for the question! 
Could you please also add @azafeiropoulos (github username) so as to be all the same page?

**Comment by carlos-f-parada** [comment]
@pkarkazis, @tsoenen, @efotopoulou, @mtouloup, @ekapassa @azafeiropoulos
The SLAs, Policies should be able first to provision new alerts on certain metrics for some thresholds. After that, the Monitoring should publish this in the same topics as today, and the consumers should go there and get what they want. Monitoring should not be aware of who wants a particular threshold. This is what was decided some weeks ago regarding Policy and should apply for SLA too (BTW, by this time this API extension should be ready or very close). See these minutes to recap (https://git.cs.upb.de/5gtango/generalInfo/wikis/tango-wp5-2018-05-22_14h).
Any comments/disagreements?

**Comment by jbonnet** [comment]
I agree, @carlos-f-parada, my doubt is about the MANO->Monitoring: can we make it so that all three consumers (Monitoring, SLA and Policies) can consume from there, or do we need different topics? If yes, why?

**Comment by carlos-f-parada** [comment]
@pkarkazis, @tsoenen, @efotopoulou, @mtouloup, @ekapassa @azafeiropoulos
There is another notification to the GK which is used when the whole process is completed. THis one should be more appropriate.

**Comment by ekapassa** [comment]
@carlos-f-parada From the SLA Manager's  perspective it is ok to proceed with the process you described above.     

@pkarkazis @tsoenen  @efotopoulou @mtouloup
Also, I would like to point out what @jbonnet mentions. Indeed it is another notification, but  new service instance information (from the MANO) should be available also to the SLA Manager (and maybe policy manager). So, if this ns instantiation information is available already to the Monitoring though a topic, I think that there is no need for repeating. All three components should listen to that topic and get what needed.        
 
For the SLA Manager this info include information for example: instantiated ns uuid, customer id, customer email/username, selectred sla uuid etc.

**Comment by tsoenen** [comment]
As of now, the MANO informs the Monitoring Manager of a new NS instantiation through a REST API. After that, the Monitoring Manager starts sending data on the requested metrics through the message broker.

What we can do is that the MANO extends its 'completion' message to the GK to include the topic the Monitoring Manager is sending data on. The GK can then share it with the SLA and Policy Manager so they know where to listen, or they can directly eavesdrop the message to the GK.

This process doesn't allow SLA and Policy Manager to add metrics / thresholds however, so we would need to add a way for them to add these.

**Comment by pkarkazis** [comment]
@jbonnet, @carlos-f-parada, @trakadasp, @tsoenen, @efotopoulou, @mtouloup, @ekapassa @azafeiropoulos
Until now, SLA Manager informs the Monitoring Manager directly (using a Rest API) on the initiation of a new NS. However, the approach of the usage of a common topic which is going to be consumed from all three components is very attractive.

**Comment by mtouloup** [comment]
I share the same view with @Panos. A new topic shared with all three components would be a nice to have!

--
Marios Touloupos, M.Sc.
University of Piraeus
Phone: +30 6975620696
Skype: touloupos1
Email: mtouloup@unipi.gr

**Comment by jbonnet** [comment]
Exactly, @pkarkazis, there's little sense in having a MANO that's message-based (with all the flexibility it brings) and the... is dependent on a specific REST API... how difficult would it be to change this REST API into a message-based one?

@ekapassa, @mtouloup:

> ...this info include information for example: instantiated ns uuid, customer id, customer email/username, selectred sla uuid etc.

That's the reason I've asked if consuming the original message of the instantaition request would make more sense. Note that you still need to wait for the message of the MANO with the result of the instantiation request

**Comment by pkarkazis** [comment]
@jbonnet 
It's not difficult but we will need some time to implemented and to test it. The quickest approach is SLA Manager to publish the same message in the message broker instead of the API and I will implement a new functionality from the Monitoring Manager side in order to consume it.

**Comment by carlos-f-parada** [comment]
@jbonnet, @carlos-f-parada, @trakadasp, @tsoenen, @efotopoulou, @mtouloup, @ekapassa @azafeiropoulos
So it seems we agree on changing communication MANO-Mon to message-based, sharing this also to SLA and Policy.
@pkarkazis let me know if I get your last point... so you are proposing to make messaging developments and start receiving new provision of new metrics from the SLA Manager via messaging (the same for Policy I suppose). Then, the MANO will be move to leave REST and start using messaging. Is that the "migration plan" you suggest?

**Comment by jbonnet** [comment]
@pkarkazis, @carlos-f-parada  (cc: @tsoenen ),

Note that the MANO also needs some effort to change from REST to message-based

**Comment by carlos-f-parada** [comment]
@jbonnet Yep. But don't worry, as this is not urgent. We can leave with both for the transition period. Anyway, I suppose it will not be hard since, as you say, MANO is mainly messaging based. But @tsoenen can better tell us about the real effort.

**Comment by tsoenen** [comment]
@jbonnet @carlos-f-parada Yes, the impact on the MANO will be minimal, as I understood that the payload will remain the same. Instead of sending it with REST, I just need to post on a topic.

**Comment by ekapassa** [comment]
@tsoenen @jbonnet @carlos-f-parada Perfect regarding the posting on a topic. Can we agree on a time plan for that @tsoenen?? I dont want to put pressure, I am just asking in order to know if some sla features that need this info will be available for 30th June, or we will leave it for transition period.

**Comment by tsoenen** [comment]
@ekapassa From the moment that the Monitoring Manager accepts topic-based requests, I can make the change. So if the timeline of @pkarkazis fits in the next week, we can do it for this release.
